name: Run tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: blackenedgold/idris:1.3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: idris --testpkg deriving.ipkg
